import { test, expect } from '@playwright/test';

test('testActualizar_perfil', async ({ page }) => {
  await page.goto('https://buggy.justtestit.org/profile');
  await page.goto('https://buggy.justtestit.org/');
  await page.getByPlaceholder('Login').fill('andres11');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('Perez12345$');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Hi, Carlos Andres').click();
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').press('ArrowLeft');
  await page.getByLabel('First Name').press('ArrowLeft');
  await page.getByLabel('First Name').press('ArrowLeft');
  await page.getByLabel('First Name').press('ArrowLeft');
  await page.getByLabel('First Name').press('ArrowLeft');
  await page.getByLabel('First Name').press('ArrowLeft');
  await page.getByLabel('First Name').fill('Andres');
  await page.getByLabel('First Name').dblclick();
  await page.getByLabel('First Name').fill('Andres');
  await page.getByLabel('Last Name').dblclick();
  await page.getByLabel('Last Name').fill('Perez');
  await page.locator('div').filter({ hasText: 'Basic Login First Name First' }).nth(2).click();
  await page.getByLabel('Address').click();
  await page.getByLabel('Address').fill('carrera 37');
  await page.locator('div').filter({ hasText: 'Basic Login First Name First' }).nth(2).click();
  await page.getByLabel('Phone').dblclick();
  await page.getByLabel('Phone').fill('555555');
  await page.getByLabel('Hobby').selectOption('Working');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('The profile has been saved').first().click();
  await page.getByText('The profile has been saved').first().click();
  await page.getByText('The profile has been saved').first().click();
});

//Aquí se hace el cambio de clave y el intento de cambio de nombre pero con los campos vacíos
test('testCambiar_clave', async ({ page }) => {
  await page.goto('https://buggy.justtestit.org/profile');
  await page.goto('https://buggy.justtestit.org/');
  await page.getByRole('link', { name: 'Register' }).click();
  await page.getByLabel('Login').click();
  await page.getByLabel('Login').click();
  await page.getByLabel('Login').fill('juansd');
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').fill('juan');
  await page.getByLabel('Last Name').click();
  await page.getByLabel('Last Name').fill('sdel');
  await page.getByLabel('Password', { exact: true }).click();
  await page.getByLabel('Password', { exact: true }).fill('Juansd123$');
  await page.getByLabel('Confirm Password').click();
  await page.getByLabel('Confirm Password').fill('Juansd123$');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByPlaceholder('Login').click();
  await page.getByPlaceholder('Login').fill('juansd');
  await page.getByRole('navigation').locator('input[name="password"]').click();
  await page.getByRole('navigation').locator('input[name="password"]').fill('Juansd123$');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.getByLabel('Current Password').click();
  await page.getByLabel('Current Password').fill('Juansd123$');
  await page.getByLabel('New Pasword').click();
  await page.getByLabel('New Pasword').fill('Sebas987*');
  await page.getByLabel('Confirm Password').click();
  await page.getByLabel('Confirm Password').fill('Sebas987*');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('The profile has been saved').first().click();
  await page.getByText('The profile has been saved').first().click();
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').fill('');
  await page.getByLabel('Last Name').dblclick();
  await page.getByLabel('Last Name').fill('');
  await page.getByText('Login First Name First Name').click();
  await page.getByText('Buggy Rating Hi, juan Profile Logout BuggyCarsRating Basic Login First Name').click();
  await page.getByText('Last Name is required').click();
  await page.getByText('First Name is required').click();
  await page.getByText('Buggy Rating Hi, juan Profile Logout BuggyCarsRating Basic Login First Name').click();
  await page.getByText('Last Name is required').click();
  await page.getByText('First Name is required').click();
});

